FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copying the source code
COPY . .

# Exposing the port the app runs on
EXPOSE 7070

COPY entrypoint.sh /usr/src/app/
RUN chmod +x /usr/src/app/entrypoint.sh
ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]
