FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copying the source code
COPY . .

# Exposing the port the app runs on
EXPOSE 3000

# Command to run the application using nodemon
CMD ["npm", "run", "dev"]
